version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: dacorrado_mysql
    restart: always
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: dacorrado
      MYSQL_USER: dacorrado
      MYSQL_PASSWORD: dacorrado1234
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
